package gearshop.domain;
// Generated Mar 17, 2017 5:12:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BuilderAbsence generated by hbm2java
 */
@Entity
@Table(name="BUILDER_ABSENCE"
    ,catalog="gearshop"
)
public class BuilderAbsence  implements java.io.Serializable {


     private Long id;
     private long builderId;

    public BuilderAbsence() {
    }

    public BuilderAbsence(long builderId) {
       this.builderId = builderId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="BUILDER_ID", nullable=false)
    public long getBuilderId() {
        return this.builderId;
    }
    
    public void setBuilderId(long builderId) {
        this.builderId = builderId;
    }




}


