package gearshop.domain;
// Generated Mar 17, 2017 5:12:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustomerHist generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER_HIST"
    ,catalog="gearshop"
)
public class CustomerHist  implements java.io.Serializable {


     private Long id;
     private long customerId;

    public CustomerHist() {
    }

    public CustomerHist(long customerId) {
       this.customerId = customerId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="CUSTOMER_ID", nullable=false)
    public long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }




}


