package gearshop.domain;
// Generated Mar 17, 2017 5:12:54 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name="INVOICE"
    ,catalog="gearshop"
)
public class Invoice  implements java.io.Serializable {


     private Long id;
     private long customerId;
     private Date invoiceDate;
     private String poNbr;
     private BigDecimal coreCharge;
     private BigDecimal credit;
     private String message;
     private BigDecimal shippingCharge;
     private BigDecimal discountAmount;
     private String shippingVia;
     private Date createdDtm;
     private Date lastUpdtDtm;

    public Invoice() {
    }

	
    public Invoice(long customerId, Date invoiceDate, Date createdDtm, Date lastUpdtDtm) {
        this.customerId = customerId;
        this.invoiceDate = invoiceDate;
        this.createdDtm = createdDtm;
        this.lastUpdtDtm = lastUpdtDtm;
    }
    public Invoice(long customerId, Date invoiceDate, String poNbr, BigDecimal coreCharge, BigDecimal credit, String message, BigDecimal shippingCharge, BigDecimal discountAmount, String shippingVia, Date createdDtm, Date lastUpdtDtm) {
       this.customerId = customerId;
       this.invoiceDate = invoiceDate;
       this.poNbr = poNbr;
       this.coreCharge = coreCharge;
       this.credit = credit;
       this.message = message;
       this.shippingCharge = shippingCharge;
       this.discountAmount = discountAmount;
       this.shippingVia = shippingVia;
       this.createdDtm = createdDtm;
       this.lastUpdtDtm = lastUpdtDtm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="CUSTOMER_ID", nullable=false)
    public long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INVOICE_DATE", nullable=false, length=19)
    public Date getInvoiceDate() {
        return this.invoiceDate;
    }
    
    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    
    @Column(name="PO_NBR", length=45)
    public String getPoNbr() {
        return this.poNbr;
    }
    
    public void setPoNbr(String poNbr) {
        this.poNbr = poNbr;
    }

    
    @Column(name="CORE_CHARGE", precision=5)
    public BigDecimal getCoreCharge() {
        return this.coreCharge;
    }
    
    public void setCoreCharge(BigDecimal coreCharge) {
        this.coreCharge = coreCharge;
    }

    
    @Column(name="CREDIT", precision=5)
    public BigDecimal getCredit() {
        return this.credit;
    }
    
    public void setCredit(BigDecimal credit) {
        this.credit = credit;
    }

    
    @Column(name="MESSAGE", length=125)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="SHIPPING_CHARGE", precision=5)
    public BigDecimal getShippingCharge() {
        return this.shippingCharge;
    }
    
    public void setShippingCharge(BigDecimal shippingCharge) {
        this.shippingCharge = shippingCharge;
    }

    
    @Column(name="DISCOUNT_AMOUNT", precision=5)
    public BigDecimal getDiscountAmount() {
        return this.discountAmount;
    }
    
    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    
    @Column(name="SHIPPING_VIA", length=45)
    public String getShippingVia() {
        return this.shippingVia;
    }
    
    public void setShippingVia(String shippingVia) {
        this.shippingVia = shippingVia;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DTM", nullable=false, length=19)
    public Date getCreatedDtm() {
        return this.createdDtm;
    }
    
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDT_DTM", nullable=false, length=19)
    public Date getLastUpdtDtm() {
        return this.lastUpdtDtm;
    }
    
    public void setLastUpdtDtm(Date lastUpdtDtm) {
        this.lastUpdtDtm = lastUpdtDtm;
    }




}


