package gearshop.domain;
// Generated Mar 17, 2017 5:12:54 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProductHist generated by hbm2java
 */
@Entity
@Table(name="PRODUCT_HIST"
    ,catalog="gearshop"
)
public class ProductHist  implements java.io.Serializable {


     private Long id;
     private long productId;

    public ProductHist() {
    }

    public ProductHist(long productId) {
       this.productId = productId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="PRODUCT_ID", nullable=false)
    public long getProductId() {
        return this.productId;
    }
    
    public void setProductId(long productId) {
        this.productId = productId;
    }




}


