package gearshop.domain;
// Generated Mar 17, 2017 5:12:54 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name="PRODUCT"
    ,catalog="gearshop"
)
public class Product  implements java.io.Serializable {


     private Long id;
     private String partNbr;
     private String description;
     private BigDecimal price;
     private Integer inventory;
     private BigDecimal weight;
     private String upc;
     private Date createdDtm;
     private Date lastModifiedDtm;

    public Product() {
    }

	
    public Product(String partNbr, BigDecimal price, Date createdDtm, Date lastModifiedDtm) {
        this.partNbr = partNbr;
        this.price = price;
        this.createdDtm = createdDtm;
        this.lastModifiedDtm = lastModifiedDtm;
    }
    public Product(String partNbr, String description, BigDecimal price, Integer inventory, BigDecimal weight, String upc, Date createdDtm, Date lastModifiedDtm) {
       this.partNbr = partNbr;
       this.description = description;
       this.price = price;
       this.inventory = inventory;
       this.weight = weight;
       this.upc = upc;
       this.createdDtm = createdDtm;
       this.lastModifiedDtm = lastModifiedDtm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="PART_NBR", nullable=false, length=45)
    public String getPartNbr() {
        return this.partNbr;
    }
    
    public void setPartNbr(String partNbr) {
        this.partNbr = partNbr;
    }

    
    @Column(name="DESCRIPTION", length=125)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="PRICE", nullable=false, precision=5)
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="INVENTORY")
    public Integer getInventory() {
        return this.inventory;
    }
    
    public void setInventory(Integer inventory) {
        this.inventory = inventory;
    }

    
    @Column(name="WEIGHT", precision=5)
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    
    @Column(name="UPC", length=45)
    public String getUpc() {
        return this.upc;
    }
    
    public void setUpc(String upc) {
        this.upc = upc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DTM", nullable=false, length=19)
    public Date getCreatedDtm() {
        return this.createdDtm;
    }
    
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_MODIFIED_DTM", nullable=false, length=19)
    public Date getLastModifiedDtm() {
        return this.lastModifiedDtm;
    }
    
    public void setLastModifiedDtm(Date lastModifiedDtm) {
        this.lastModifiedDtm = lastModifiedDtm;
    }




}


