package gearshop.domain;
// Generated Mar 17, 2017 5:12:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UnitHist generated by hbm2java
 */
@Entity
@Table(name="UNIT_HIST"
    ,catalog="gearshop"
)
public class UnitHist  implements java.io.Serializable {


     private Long id;
     private long unitId;
     private String event;
     private String eventDesc;
     private Date createdDtm;
     private Date lastUpdtDtm;

    public UnitHist() {
    }

	
    public UnitHist(long unitId, String event, Date createdDtm, Date lastUpdtDtm) {
        this.unitId = unitId;
        this.event = event;
        this.createdDtm = createdDtm;
        this.lastUpdtDtm = lastUpdtDtm;
    }
    public UnitHist(long unitId, String event, String eventDesc, Date createdDtm, Date lastUpdtDtm) {
       this.unitId = unitId;
       this.event = event;
       this.eventDesc = eventDesc;
       this.createdDtm = createdDtm;
       this.lastUpdtDtm = lastUpdtDtm;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="UNIT_ID", nullable=false)
    public long getUnitId() {
        return this.unitId;
    }
    
    public void setUnitId(long unitId) {
        this.unitId = unitId;
    }

    
    @Column(name="EVENT", nullable=false, length=45)
    public String getEvent() {
        return this.event;
    }
    
    public void setEvent(String event) {
        this.event = event;
    }

    
    @Column(name="EVENT_DESC", length=125)
    public String getEventDesc() {
        return this.eventDesc;
    }
    
    public void setEventDesc(String eventDesc) {
        this.eventDesc = eventDesc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATED_DTM", nullable=false, length=19)
    public Date getCreatedDtm() {
        return this.createdDtm;
    }
    
    public void setCreatedDtm(Date createdDtm) {
        this.createdDtm = createdDtm;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_UPDT_DTM", nullable=false, length=19)
    public Date getLastUpdtDtm() {
        return this.lastUpdtDtm;
    }
    
    public void setLastUpdtDtm(Date lastUpdtDtm) {
        this.lastUpdtDtm = lastUpdtDtm;
    }




}


