/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gearshop.ui;

import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 *
 * @author theanhha
 */
public class NavButtonPannel extends javax.swing.JPanel {

    private Supplier<Void> firstAction;
    private Supplier<Void> lastAction;
    private Supplier<Void> nextAction;
    private Supplier<Void> previousAction;

    public void setFirstAction(Supplier<Void> firstAction) {
        this.firstAction = firstAction;
    }

    public void setLastAction(Supplier<Void> lastAction) {
        this.lastAction = lastAction;
    }

    public void setNextAction(Supplier<Void> nextAction) {
        this.nextAction = nextAction;
    }

    public void setPreviousAction(Supplier<Void> previousAction) {
        this.previousAction = previousAction;
    }
    
    /**
     * Creates new form NavButtonPannel
     */
    public NavButtonPannel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstButton = new javax.swing.JButton();
        previousButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 0));

        firstButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1489817715_step-backward.png"))); // NOI18N
        firstButton.setMaximumSize(new java.awt.Dimension(50, 36));
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });
        add(firstButton);

        previousButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1489817689_caret-left.png"))); // NOI18N
        previousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousButtonActionPerformed(evt);
            }
        });
        add(previousButton);

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1489817595_caret-right.png"))); // NOI18N
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        add(nextButton);

        lastButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/1489817431_step-forward.png"))); // NOI18N
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });
        add(lastButton);
    }// </editor-fold>//GEN-END:initComponents

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        this.firstAction.get();
    }//GEN-LAST:event_firstButtonActionPerformed

    private void previousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousButtonActionPerformed
        this.previousAction.get();
    }//GEN-LAST:event_previousButtonActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        this.nextAction.get();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        this.lastAction.get();
    }//GEN-LAST:event_lastButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton firstButton;
    private javax.swing.JButton lastButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton previousButton;
    // End of variables declaration//GEN-END:variables
}
